language: python

python:
  - "3.5"
  - "3.6"

sudo: false

env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=master

matrix:
  fast_finish: true
  allow_failures:
    - env: DJANGO=master
    - env: DJANGO=2.0

install:
  - pip install tox tox-travis
  - pip install coveralls

script:
  - tox

after_success:
  - coveralls

notifications:
  email: false
